return {
    name="MadelineCrystal/GiveCrystalDashesTrigger",
    placements={
        name="main",
        data={
            oneTime=true,
            amt=1,
            setMode="add",
            mode="enter",
        }
    },
    fieldInformation={
        mode={
            options={
                "enter",
                "exit"
            },
            editable=false
        },
        setMode={
            options={
                "add",
                "set"
            },
            editable=false
        },
        amt={
            fieldType="integer"
        },
    }
}
